#!/bin/bash

########################################################################################
#Script Name : B3 Dispatcher Tool - SFTP Streamer
#Description : Tool to transfer files between My Company and B3 via SFTP protocol.   
#Author      : Wiliam Freitas
#Email       : wiliamjf@gmail.com
#Date        : 2022-03-23
########################################################################################

# Instanciando configuracoes e funcoes:

scriptheader="/usr/local/etc/b3dispatcher/assets/properties/scriptheader"

# Verifica se o Script Header Existe:
if [ -e "${scriptheader}" ]; then

    # Se existir, instancia o script para validar configuracoes e funcoes:
    . ${scriptheader}

else

    # Se nao existir, exibe erro em tela e no log 
    msg1="Nao foi possivel carregar configuracoes e funcoes."
    msg2="Arquivo ${scriptheader} nao foi encontrado"
    echo -e "\n${red}${msg1}.${nc}"
    echo -e "\n${red}${msg2}.${nc}"
    messagelog="$msg1 $msg2"
    logmein
    exit 1

fi

# Verifica o que esta requisitando o snippet para bloquear requisicoes diretas:
block_snippet_exec

# Loga no log do sistema a acao que esse script esta realizando:
actionlog="Snippet007"
messagelog="Executando checagem de nomes de arquivos."
logmein

# Verifica se ha arquivos no diretorio raiz:
if [[ $(find $input_dir | wc -l) -ge "2" ]] ; then

    # Verifica se os nomes dos arquivos comecam com o numero da empresa:
    empresas="$(echo $empresas | sed -e "s/, /\\\|/g")"
    filteringRegexNames="$(echo $set1_files_order $set2_files_order | sed -e "s/,/\\\|/g" | sed -e "s/ //g")"
    validation_empresas="$(ls -1 $input_dir | grep -v "$filteringRegexNames")"

    if [[ ! -z $validation_empresas ]]; then

        echo -e "Nomenclaturas nao reconhecidas:\n"

        for fileName in $validation_empresas; do
        
            # Move arquivos para diretorio com falha de validacao:
            mv -f ${input_dir}/${fileName} ${failed_dir}/

            # Verifica se foi movido com sucesso:
            case $? in
               0) actionlog="Snippet007" ;
                  messagelog="Falha de validacao: Arquivo ${fileName} nao possui padrao de nome reconhecido. Arquivo movido para ${failed_dir}/" ;
                  logmein ;;
            esac; done

    fi

else

        actionlog="Snippet007"
        messagelog="Nao ha arquivos para validar nomenclatura."
        logmein

fi