#!/bin/bash

########################################################################################
#Script Name : B3 Dispatcher Tool - SFTP Streamer
#Description : Tool to transfer files between My Company and B3 via SFTP protocol.   
#Author      : Wiliam Freitas
#Email       : wiliamjf@gmail.com
#Date        : 2022-03-23
########################################################################################

# Instanciando configuracoes e funcoes:

scriptheader="/usr/local/etc/b3dispatcher/assets/properties/scriptheader"

# Verifica se o Script Header Existe:
if [ -e "${scriptheader}" ]; then

    # Se existir, instancia o script para validar configuracoes e funcoes:
    . ${scriptheader}

else

    # Se nao existir, exibe erro em tela e no log 
    msg1="Nao foi possivel carregar configuracoes e funcoes."
    msg2="Arquivo ${scriptheader} nao foi encontrado"
    echo -e "\n${red}${msg1}.${nc}"
    echo -e "\n${red}${msg2}.${nc}"
    messagelog="$msg1 $msg2"
    logmein
    exit 1

fi

# Verifica o que esta requisitando o snippet para bloquear requisicoes diretas:
block_snippet_exec

# Loga no log do sistema a acao que esse script esta realizando:
actionlog="Snippet006"
messagelog="Executando checagem de tamanho de arquivos."
logmein

# Verifica se ha arquivo no diretorio raiz
# O valor deve ser maior ou igual a 2, pois o proprio diretorio raiz
# eh contabilizado pelo find. Ou seja, a contagem comeca no 1.

if [[ $(find $input_dir | wc -l) -ge "2" ]] ; then

    # Para cada arquivo presente no diretorio raiz, realiza o loop abaixo:
    for check_file_empty in $(ls -1 $input_dir); do

        if [ $(file ${input_dir}/${check_file_empty} | grep empty) ]; then

            mv -f ${input_dir}/${check_file_empty} ${largefiles_dir}/

            case $? in
                0) actionlog="Snippet006" ;
                   messagelog="Falha de validacao: Arquivo ${check_file_empty} esta em branco. Arquivo movido para ${largefiles_dir}" ;
                   logmein ;;
            esac

        fi; done

    for fileSize in $(ls -1 $input_dir); do

        # Verifica o tamanho do arquivo. Se sim, entra no if abaixo:
        if [[ $(du -sh ${input_dir}/${fileSize} | awk '{print$1}' | grep "M"  | sed -e "s/M//g" | cut -d. -f1) -ge "${maxfilesize}" ]]; then

            # Se o arquivo nao for maior do que o tamanho limite, move o arquivo para diretorio especifico:
            mv -f ${input_dir}/${fileSize} ${largefiles_dir}/

            # Verifica se foi movido com sucesso:
            case $? in
                0) actionlog="Snippet006" ;
                messagelog="Falha de validacao: Arquivo ${fileSize} eh maior do que ${maxfilesize}MB. Arquivo movido para ${largefiles_dir}" ;
                logmein ;;
            esac

        fi; done

    # Para cada arquivo presente no diretorio raiz, realiza o loop abaixo:
    for filePhrase in $(ls -1 $input_dir); do

        # Verifica se a frase padrao para arquivos sem conteudo existe nos arquivos:

        if [[ $(grep "${phrase_error}" ${input_dir}/${filePhrase}) ]]; then
        
            mv -f ${input_dir}/${filePhrase} ${largefiles_dir}/

            # Verifica se foi movido com sucesso:
            case $? in
                0) actionlog="Snippet006" ;
                   messagelog="Falha de validacao: Arquivo ${filePhrase} nao possui conteudo para envio para a B3. Arquivo movido para ${largefiles_dir}/" ;
                   logmein ;;
            esac

        fi; done

else

        actionlog="Snippet006"
        messagelog="Nao ha arquivos para validar tamanho."
        logmein

fi