#!/bin/bash

########################################################################################
#Script Name : B3 Dispatcher Tool - SFTP Streamer
#Description : Tool to transfer files between My Company and B3 via SFTP protocol.   
#Author      : Wiliam Freitas
#Email       : wiliamjf@gmail.com
#Date        : 2022-03-23
########################################################################################

# Instanciando configuracoes e funcoes:

scriptheader="/usr/local/etc/b3dispatcher/assets/properties/scriptheader"

# Verifica se o Script Header Existe:
if [ -e "${scriptheader}" ]; then

    # Se existir, instancia o script para validar configuracoes e funcoes:
    . ${scriptheader}

else

    # Se nao existir, exibe erro em tela e no log 
    msg1="Nao foi possivel carregar configuracoes e funcoes."
    msg2="Arquivo ${scriptheader} nao foi encontrado"
    echo -e "\n${red}${msg1}.${nc}"
    echo -e "\n${red}${msg2}.${nc}"
    messagelog="$msg1 $msg2"
    logmein
    exit 1

fi

# Verifica o que esta requisitando o snippet para bloquear requisicoes diretas:
block_snippet_exec

# Loga no log do sistema a acao que esse script esta realizando:
actionlog="Snippet001"
messagelog="Exibindo a ajuda da tool"
logmein

clear

# Uma apresentacao simpatica:
echo -e "\n${cyn}B3 Dispatcher aos seus servicos!${nc}"

# Breve descricao:
echo -e "\nDispatcher eh um tool orquestrador que envia e recebe arquivos de e para a B3."
echo -e "Aqui estao algumas formas de interagir com o Dispatcher."

# Formas de uso:
echo -e "\nForma de uso: ${cyn}${tool_name}${nc} ${pur}--parametro${nc}"

# Lista de parametros:
echo -e "\nE esses sao os parametros:\n"
echo -e " ${pur}--list${nc}: lista arquivos validados e prontos para envio;"
echo -e " ${pur}--report${nc}: lista arquivos com problema de validacao ou reportados pela B3;"
echo -e " ${pur}--validate${nc}: valida os arquivos e os prepara para envio;"
echo -e " ${pur}--sendfiles${nc}: valida os arquivos e os envia para a B3."

echo -e "\nHa parametros adicionais caso queira consultar configuracoes ou logs:\n"

echo -e " ${pur}--printvars${nc}: lista todas configuracoes da tool."
echo -e " ${pur}--taillog${nc}: exibe logs do b3dispatcher em tempo real."

echo -e "\nImportante:\n"

 echo -e "1 - Voce pode utilizar o Dispatcher em modo grafico com o comando ${cyn}${cli_name}${nc}."
 echo -e "2 - Consulte sempre o arquivo de log do sistema para obter maiores detalhes sobre as operacoes do Dispatcher.\n"