#!/usr/bin/bash

########################################################################################
#Script Name : B3 Dispatcher Tool - SFTP Streamer
#Description : Tool to transfer files between My Company and B3 via SFTP protocol.   
#Author      : Wiliam Freitas
#Email       : wiliamjf@gmail.com
#Date        : 2022-03-23
########################################################################################

# O arquivo scriptheader instancia configuracoes e verifica se o arquivo de funcoes existe.

scriptheader="/usr/local/etc/b3dispatcher/assets/properties/scriptheader"

# Verifica se o scriptheader existe.
if [ -e "${scriptheader}" ]; then

    # Caso exista, executa o arquivo.
    . ${scriptheader}

else

    # Caso nao exista, dara erro e aborda o script:
    echo -e "\nNao foi possivel carregar configuracoes e funcoes."
    echo -e "Arquivo ${scriptheader} nao foi encontrado\n"
    exit 1

fi

# Loga no log do sistema a acao que esse script esta realizando:
actionlog="Iniciando"
messagelog="Inicializado ${tool_name} por ${USER}."
logmein

# Determina horario de inicio da execucao:
start_execution_hour=$(date +%H)

# Determina o minuto de inicio da execucao:
start_execution_minute=$(date +%M)

# Se nenhum parametro foi informado, exibe a ajuda:
if [ -z $1 ]; then

    messagelog="Exibindo ajuda para ${USER}"
    logmein
    usage

# Valida arquivos: 
elif [ $1 == "--validate" ]; then

    messagelog="Executando opcao --validate"
    logmein

    # Verificando se ha processos em execucao:
    get_lock

    # Define silent desativado:
    silent=0
    # Define mode validate:
    mode=validate

    # Se o --silent foi informado, desativa o mode silent:
    if [[ $2 == "--silent" ]]; then

        silent=1

    fi

    # Reprocessa arquivos recusados pela B3 (se houver):
    function_run_chk_reprocess

    # Verifica nome dos arquivos no diretorio inputdir 
    function_run_chk_file_name

    # Verifica o tamanho dos arquivos no inputdir:    
    function_run_chk_file_size

    # Move arquivos do inputdir para queue:
    function_run_move_files

    # Remove o arquivo de lock:
    del_lock

# Lista arquivos validados prontos para serem enviados para B3:
elif [ $1 == "--list" ]; then

    # Logando opcao selecionada:
    messagelog="Executando opcao --list"
    logmein

    # Logando acao executada:
    function_list_queues

# Exibe todas as configuracoes persistidas
elif [ $1 == "--printvars" ]; then

    grep '=' ${config_home}/${tool_name}.conf  | grep -v ^#

# Exibe o log em tempo real da tool
elif [ $1 == "--taillog" ]; then

    tail_logs

# Exibe report. O report eh composto por arquivos que falharam na validacao ou recusados pela b3:
elif [ $1 == "--report" ]; then

    messagelog="Executando opcao --reports"
    logmein

    # Exibe os reports de erro:
    show_reports

# Envia arquivos para a B3:
elif [ $1 == "--sendfiles" ]; then

    messagelog="Executando opcao --sendfiles"
    logmein

    # Verificando se ha processos em execucao:
    get_lock

    # Se o silent nao foi passado, exibe informacoes na tela:
    silent=0

    # Mode sendfiles (files, ok?)
    mode=sendfiles

    # Se o silent foi passado, nao printa nada na tela:
    if [[ $2 == "--silent" ]]; then

        silent=1

    fi

    # Verifica se ha arquivos no diretorio de envio e que nao foram enviados
    function_run_chk_queue

    # Reprocessa arquivos recusados pela B3 (se houver):
    function_run_chk_reprocess

    # Verifica nome dos arquivos no diretorio inputdir 
    function_run_chk_file_name

    # Verifica o tamanho dos arquivos no inputdir:    
    function_run_chk_file_size

    # Move arquivos do inputdir para queue:
    function_run_move_files
    
    # Envia arquivos:    
    function_send

    # Chama a function para fazer o calculo do tempo de execucao:
    function_calculate_execution_time

    # Remove o arquivo de lock:
    del_lock

else

    usage

fi
    
